### ISSUE TITLE
💔 Testing is broken

### ISSUE THREAD

**Issue by favonia** [RedPRL/cooltt#270] opened 2021-07-31 12:36 UTC
It seems #257 has some (unintended?) interactions with other PRs. After merging all of them, the current main branch is broken. There is always a question about whether it is the program or the testing at fault---I checked the output diff and it seems it's the program that is buggy, not the expected output.

**Comment by jonsterling** [comment] 2021-07-31 14:26
oops lol

**Comment by TOTBWF** [comment] 2021-07-31 15:45
Looks like an off by one error somewhere, let's just revert it and then we can take another look at it.

**Comment by TOTBWF** [comment] 2021-08-04 21:16
This is also popping up for @jonsterling locally, so perhaps something more sinister is afoot.

**Comment by jonsterling** [comment] 2021-08-04 21:22
are you able to reproduce it?

**Comment by TOTBWF** [comment] 2021-08-04 21:26
I get _a_ failure, but it's only because we haven't updated the snapshot for the test added in https://github.com/RedPRL/cooltt/pull/274/commits/df650f4551d11f17aab1a45b32a4b76ee12d9ece

**Comment by jonsterling** [comment] 2021-08-04 21:57
i’ll paste the failure i get

**Comment by jonsterling** [comment] 2021-08-12 19:30
@TOTBWF I can still confirm that the test is broken on master, by just running the cooltt executable on the following input:

```
import prelude

def cone-of-silence-hcom  (A : type) (p : 𝕀 → A) (q : (i : 𝕀) → sub A {i=0} {p 1}) : path A {p 0} {q 1} :=
  i => hcom A 0 1 {∂ i} {!!}
```

The output is:

```
[stdin]:4.26-4.30 [Info]:
  Emitted hole:
    A : type
    p : (_x : 𝕀) → A
    q : (i : 𝕀) → sub A {i = 0} {p 1}
    i : 𝕀
    |- ? : (_x : 𝕀) → (_x₁ : [ _x = 0 ∨ i = 0 ∨ i = 1 ]) → A


[stdin]:4.7-4.30 [Error]:
  Expected #0 A p q i 1 * =
           [ i = 0 => p 0 | i = 1 => q 1 ]
           : A

cooltt: encountered one or more errors
```

**Comment by jonsterling** [comment] 2021-08-12 19:32
Oh, I think I misunderstood. Perhaps this error is actually expected? If so (meaning it is a test that is meant to fail), we should add a new top-level form `fail [decl...]`, since I do not want our tests to contain files whose execution results in an error return code.

**Comment by TOTBWF** [comment] 2021-08-12 22:46
I've created #276, which adds the `fail` form, and also updates the test suite accordingly!

**Comment by TOTBWF** [comment] 2021-08-31 23:31
Have we had any more issues with this? If not, we should probably close it.

**Closed** 2021-08-31 23:42 UTC
